### ISSUE TITLE
#writeHeader: does not use fieldWriter

### ISSUE THREAD

**Issue by marceltaeumel** [svenvc/NeoCSV#11]
It is not possible to write an unquoted header because `#writeHeader:` does always send `#writeQuotedField:` instead of what is configured via `fieldWriter`. My goal here is to write a CSV file that should be consumed outside the Smalltalk world.

**Comment by svenvc** [comment]
I agree that it would be better for #writeHeader: to use #writeField: since that does indeed give more flexibility, I will change it.

But I disagree with your suggestion that quoting fields or headers would not be standard, on the contrary, I have not yet encountered any system that fails with quotes, but of course, YMMV.

**Comment by marceltaeumel** [comment]
Ah, I didn't know that. Thanks. :-)

**Comment by svenvc** [comment]
https://github.com/svenvc/NeoCSV/commit/f82f70e56a269a4e07be3886337c0ec7866e4d99
